//! Generator — the answer-generation half of RAG.
//!
//! After retrieval, the retrieved chunks are assembled into a prompt context
//! and passed to a [`Generator`] to produce a natural-language answer. The
//! default [`LocalEchoGenerator`] runs offline: it formats the retrieved
//! passages as a citation block (the contract a real LLM provider would
//! consume) and returns a templated response. A real LLM provider plugs in
//! via the trait, behind the `llm` feature.

use serde::{Deserialize, Serialize};

use crate::chunk::Chunk;
use crate::vectorstore::SearchResult;

/// A generated answer with its supporting sources.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GeneratedAnswer {
    /// The generated natural-language answer.
    pub answer: String,
    /// The chunks used as context, in the order cited.
    pub sources: Vec<Chunk>,
    /// Name of the generator that produced this answer.
    pub provider: String,
}

/// The interface for turning a question + retrieved context into an answer.
pub trait Generator: Send + Sync {
    fn name(&self) -> &'static str;
    fn generate(&self, question: &str, context: &[SearchResult]) -> GeneratedAnswer;
}

/// Key-less offline generator. Formats context as a citation block and returns
/// a templated answer. Use this to exercise the full RAG loop; swap in a real
/// LLM for actual generation.
pub struct LocalEchoGenerator {
    /// Maximum characters of context to include.
    pub max_context_chars: usize,
}

impl Default for LocalEchoGenerator {
    fn default() -> Self {
        LocalEchoGenerator {
            max_context_chars: 4000,
        }
    }
}

impl Generator for LocalEchoGenerator {
    fn name(&self) -> &'static str {
        "local-echo"
    }

    fn generate(&self, question: &str, context: &[SearchResult]) -> GeneratedAnswer {
        if context.is_empty() {
            return GeneratedAnswer {
                answer: format!(
                    "No relevant passages were found to answer: \"{question}\". \
                     Try ingesting more documents or rephrasing the question."
                ),
                sources: Vec::new(),
                provider: "local-echo".to_string(),
            };
        }

        // Build the context block (what a real LLM would receive).
        let mut context_block = String::new();
        let mut sources = Vec::new();
        let mut used = 0usize;

        for (i, result) in context.iter().enumerate() {
            if used + result.chunk.text.len() > self.max_context_chars {
                break;
            }
            context_block.push_str(&format!("[{}] {}\n", i + 1, result.chunk.text));
            sources.push(result.chunk.clone());
            used += result.chunk.text.len();
        }

        // Templated answer — a real generator would call an LLM here.
        let answer = format!(
            "Based on {} retrieved passage(s), here is what the document says about \"{question}\":\n\n\
             {context_block}\n\
             (Generated by the local-echo placeholder. Configure an LLM Generator for synthesized answers.)",
            sources.len()
        );

        GeneratedAnswer {
            answer,
            sources,
            provider: "local-echo".to_string(),
        }
    }
}

#[cfg(feature = "llm")]
pub mod http {
    //! HTTP-backed LLM generator stub (behind the `llm` feature).
    use super::{GeneratedAnswer, Generator};
    use crate::vectorstore::SearchResult;

    pub struct HttpGenerator {
        pub endpoint: Option<String>,
        pub api_key: Option<String>,
        pub model: Option<String>,
    }

    impl Default for HttpGenerator {
        fn default() -> Self {
            HttpGenerator {
                endpoint: std::env::var("OPENDOCU_LLM_ENDPOINT").ok(),
                api_key: std::env::var("OPENDOCU_LLM_API_KEY").ok(),
                model: std::env::var("OPENDOCU_LLM_MODEL").ok(),
            }
        }
    }

    impl Generator for HttpGenerator {
        fn name(&self) -> &'static str {
            "http-llm"
        }
        fn generate(&self, _question: &str, _context: &[SearchResult]) -> GeneratedAnswer {
            // TODO: assemble a chat prompt, POST to self.endpoint with the
            // retrieved context, and parse the generated answer.
            GeneratedAnswer {
                answer: "[HTTP LLM generator not yet implemented — see TODO]".into(),
                sources: _context.iter().map(|r| r.chunk.clone()).collect(),
                provider: "http-llm-stub".into(),
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::embeddings::{Embedding, LocalHashEmbedder};
    use crate::vectorstore::SearchResult;

    fn fake_results(texts: &[&str]) -> Vec<SearchResult> {
        texts
            .iter()
            .enumerate()
            .map(|(i, t)| SearchResult {
                chunk: Chunk {
                    text: t.to_string(),
                    index: i,
                    start_offset: 0,
                    token_estimate: 5,
                    metadata: Default::default(),
                },
                score: 0.9 - i as f64 * 0.1,
                rank: i + 1,
            })
            .collect()
    }

    #[test]
    fn generates_with_context() {
        let g = LocalEchoGenerator::default();
        let results = fake_results(&["Revenue grew 20%.", "Profit doubled."]);
        let answer = g.generate("How did revenue change?", &results);
        assert!(answer.answer.contains("Revenue grew 20%"));
        assert_eq!(answer.sources.len(), 2);
        assert_eq!(answer.provider, "local-echo");
    }

    #[test]
    fn empty_context_gives_helpful_message() {
        let g = LocalEchoGenerator::default();
        let answer = g.generate("anything", &[]);
        assert!(answer.answer.contains("No relevant passages"));
        assert!(answer.sources.is_empty());
    }

    #[test]
    fn respects_context_limit() {
        let g = LocalEchoGenerator { max_context_chars: 20 };
        let results = fake_results(&["short", "another one here that is longer"]);
        let answer = g.generate("q", &results);
        // Should include the first chunk but stop before the second exceeds budget.
        assert!(answer.sources.len() <= 2);
    }

    #[test]
    fn unused_embedder_compiles() {
        // Ensure the module still references Embedding for feature-gated parity.
        let _e = Embedding {
            vector: vec![0.0],
            model: "test".to_string(),
        };
        let _emb = LocalHashEmbedder::new(8);
    }
}
